id: I91B91D05
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:52:37.038428'
last_modified: '2022-05-30T18:52:37.038434'
parser: null
source_metadata:
  title: Dongak Chökyi Gyatso
  language: bo
  description: 'Texts by Dongak Chökyi Gyatso (mdo sngags chos kyi rgya mtsho, 1903–1957)
    aka Tulku Sungrab (sprul sku gsung rab) of Pal Nyenmo Monastery in Golok:'
  volume:
    fFC46:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      base_file: fFC46.txt
      order: 1
      parent: Advice
    f61C1:
      title: Commentary on Some Terms from the Great Perfection
      base_file: f61C1.txt
      order: 2
      parent: Dzogchen
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
